export const PDF_FILE = 'PDF_FILE';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const CAMBIAR_DATOS_USUARIO = 'CAMBIAR_DATOS_USUARIO';
export const OBTENER_DATOS_USUARIO = 'OBTENER_DATOS_USUARIO';
export const SET_MENSAJE = 'SET_MENSAJE';

export const ENVIAR_DATOS_ACFT = 'ENVIAR_DATOS_ACFT';
export const OBTENER_DATOS_ACFT = 'OBTENER_DATOS_ACFT';
export const ELIMINAR_ACFT = 'ELIMINAR_ACFT';

export const ACFT_CARGADA_CORRECTA = 'ACFT_CARGADA_CORRECTA';
export const LIMPIAR_CARGA = 'LIMPIAR_CARGA';


